// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EventLogVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "EventLogVS.a9f6a6f5-4752-4c4d-a142-15340fc800af";
        public const string Name = "Event Timeline";
        public const string Description = @"Logs all events from the IDE in a timeline in a separate Output Window pane. It let's you diagnose issues and gives you a historic view of your actions in Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "log, history, timeline, time, events";
    }
}
